function createfigure(Vertices1, Faces1, FaceVertexCData1, Vertices2, Faces2, FaceVertexCData2)
%CREATEFIGURE(Vertices1, Faces1, FaceVertexCData1, Vertices2, Faces2, FaceVertexCData2)
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  VERTICES2:  patch vertices
%  FACES2:  patch faces
%  FACEVERTEXCDATA2:  patch facevertexcdata

%  Auto-generated by MATLAB on 01-Jul-2019 17:10:20

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);

% Create patch
patch('Parent',axes1,'Vertices',Vertices1,'Faces',Faces1,'FaceColor','flat',...
    'FaceVertexCData',FaceVertexCData1);

% Create patch
patch('Parent',axes1,'Vertices',Vertices2,'Faces',Faces2,'FaceColor','flat',...
    'FaceVertexCData',FaceVertexCData2);

% Create zlabel
zlabel('Elev');

% Create ylabel
ylabel('Long');

% Create xlabel
xlabel('Lat');

% Create title
title('Map');

view(axes1,[44 -9.19999999999998]);
axis(axes1,'square');
